volumes:
  pg_data:
  static:

services:
  db:
    image: "postgres:17.6"
    env_file: ./dem4/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    build: ./dem4/
    env_file: ./dem4/.env
    volumes:
      - static:/backend_static/
    depends_on:
      - db

  nginx:
    build: ./nginx/
    volumes:
      - static:/var/html/static/
    ports:
      - 8000:80
