volumes:
  pg_data:
  static:

services:
  db:
    image: "postgres:17.6"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    image: juniorrf/django-dem4
    env_file: .env
    volumes:
      - static:/backend_static/
    depends_on:
      - db

  nginx:
    image: juniorrf/nginx-dem4
    volumes:
      - static:/var/html/static/
    ports:
      - 8000:80
    depends_on:
      - django