# Generated by Django 5.1.1 on 2025-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent')),
                ('path', models.CharField(max_length=255, verbose_name='Посещенная страница')),
                ('referer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реферер')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='Время посещения')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
    ]
