# Generated by Django 5.1.1 on 2025-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='user',
            field=models.CharField(default='неавторизованный', max_length=255, verbose_name='Пользователь'),
        ),
    ]
